### ISSUE TITLE
Trouble copying folder fasrc from lab directory to your user directory

### ISSUE THREAD

**Issue by jakerbrown** [cga-harvard/Data_Science_Big_Data_Projects#1]
Tried to run the command to copy the fasrc folder from Devika's directory to mine, and received the following message, and no copied folder appeared in my directory.

[jbrown613@boslogin03 ~]$ cp /n/enos_lab/dkakkar/partisan/fasrc /n/home09/jbrown613/fasrc/

cp: omitting directory ‘/n/enos_lab/dkakkar/partisan/fasrc’

**Comment by dkakkar** [comment]
Could you try: cp -r n/enos_lab/dkakkar/partisan/fasrc /n/home09/jbrown613/

**Comment by jakerbrown** [comment]
[jbrown613@boslogin03 ~]$ cp -r /n/enos_lab/dkakkar/partisan/fasrc /n/home09/jbrown613/

cp: cannot open ‘/n/enos_lab/dkakkar/partisan/fasrc/data/sys/dashboard/batch_connect/dev/Postgres/output/72f23c6b-4639-48f7-be13-651aeb1f5263/logfile’ for reading: Permission denied

**Comment by jakerbrown** [comment]
The above code, however, does result in at least some of the folder (hard for me to tell if it is all or just partial) being copied into my directory.

**Comment by dkakkar** [comment]
> [jbrown613@boslogin03 ~]$ cp -r /n/enos_lab/dkakkar/partisan/fasrc /n/home09/jbrown613/
> 
> cp: cannot open ‘/n/enos_lab/dkakkar/partisan/fasrc/data/sys/dashboard/batch_connect/dev/Postgres/output/72f23c6b-4639-48f7-be13-651aeb1f5263/logfile’ for reading: Permission denied

It skips the logfile and I do not think you need it, so you should be good to go. Please follow the next steps and let me know if you are able to launch the app!

**Comment by jakerbrown** [comment]
Thanks!
