### ISSUE TITLE
Trouble copying the dumps to my user directory

### ISSUE THREAD

**Issue by jakerbrown** [cga-harvard/Data_Science_Big_Data_Projects#2]
[jbrown613@holy7c12307 jbrown613]$ cp /n/holyscratch01/enos_lab/dkakkar/partisan /n/holyscratch01/enos_lab/jbrown613/partisan

cp: omitting directory ‘/n/holyscratch01/enos_lab/dkakkar/partisan’

**Comment by dkakkar** [comment]
Pls use 'cp -r' while copying directories.

**Comment by dkakkar** [comment]
> [jbrown613@holy7c12307 jbrown613]$ cp /n/holyscratch01/enos_lab/dkakkar/partisan /n/holyscratch01/enos_lab/jbrown613/partisan
> 
> cp: omitting directory ‘/n/holyscratch01/enos_lab/dkakkar/partisan’
