### ISSUE TITLE
pg_restore does not work: "usvotersdb" does not exist

### ISSUE THREAD

**Issue by jakerbrown** [cga-harvard/Data_Science_Big_Data_Projects#3]
[jbrown613@holy7c12307 jbrown613]$ time pg_restore -j 8 -h localhost -p 9509 -d usvotersdb /n/holyscratch01/enos_lab/jbrown613/partisan/usvotersdbcompressed.pgsql

pg_restore: [archiver (db)] connection to database "usvotersdb" failed: FATAL:  database "usvotersdb" does not exist

**Comment by dkakkar** [comment]
> [jbrown613@holy7c12307 jbrown613]$ time pg_restore -j 8 -h localhost -p 9509 -d usvotersdb /n/holyscratch01/enos_lab/jbrown613/partisan/usvotersdbcompressed.pgsql
> 
> pg_restore: [archiver (db)] connection to database "usvotersdb" failed: FATAL: database "usvotersdb" does not exist

Did you create the DB named 'usvotersdb' while launching the instance? See the instructions for:

"Check boxes for Create DB and check box Initialize the Database store
name for the database: usvotersdb"

**Comment by jakerbrown** [comment]
Ah sorry. I did not change anything and it defaulted to 'partisandb'

**Comment by jakerbrown** [comment]
So I need to shut this all down now and start over?

**Comment by dkakkar** [comment]
> So I need to shut this all down now and start over?

You can use the same instance just replace the name of DB as "partisandb" instead of "usvotersdb" in all commands. Else you will have to start over again.
