### ISSUE TITLE
container location for omnisci has been moved

### ISSUE THREAD

**Issue by pontiggi** [cga-harvard/Data_Science_Big_Data_Projects#5]
in file dev/OmniSci/template/scripts.sh.erb line 26,  the location of the container has been moved.
The storage location listed here is no longer active

the current location is /n/singularity_images/OOD/omnisci/current/omnisci-ee-cuda_latest.sif 

```
26c26
< export container_image=/n/scratchssdlfs/singularity_images/FAS/omnisci/omnisci-ee-cuda_latest.sif
---
> export container_image=/n/singularity_images/OOD/omnisci/current/omnisci-ee-cuda_latest.sif
```

**Comment by dkakkar** [comment]
Changed!
