### ISSUE TITLE
url on wiki New-CGA-Accounts-on-FASRC

### ISSUE THREAD

**Issue by mikehinchey** [cga-harvard/Data_Science_Big_Data_Projects#6]
On https://github.com/cga-harvard/GIS_Apps_on_HPC/wiki/New-CGA-Accounts-on-FASRC the url for new has extra characters so the linked page gives an error. Changing the url to https://portal.rc.fas.harvard.edu/request/account/new works

**Comment by dkakkar** [comment]
Edited!
