### ISSUE TITLE
Modifying import script

### ISSUE THREAD

**Issue by jakerbrown** [cga-harvard/Data_Science_Big_Data_Projects#7]
In the instructions for how to load and export US-voters-database (https://github.com/cga-harvard/GIS_Apps_on_HPC/wiki/Loading-and-Exporting-US-voters-database), there is the following line:

Replace $location in the script with the location of your .csv

Is this refering to the import.sql script? To edit that, can I do that directly on the FASRC, or do I have to move the script to my home computer and update it there, before re-uploading it?

**Comment by dkakkar** [comment]
> In the instructions for how to load and export US-voters-database (https://github.com/cga-harvard/GIS_Apps_on_HPC/wiki/Loading-and-Exporting-US-voters-database), there is the following line:
> 
> Replace $location in the script with the location of your .csv
> 
> Is this refering to the import.sql script? To edit that, can I do that directly on the FASRC, or do I have to move the script to my home computer and update it there, before re-uploading it?

Yes, in the import.sql provide location of your CSV for e.g /n/holyscratch01/enos_lab/dkakkar/partisan/us-voters-2018-official.csv. You can open the script using any editor e.g vi or nano and edit it directly on FASRC.
